version: '3.9'

services:

  golang_first:
    build: ./docker/go
    container_name: golang_first
    restart: always
    ports:
      - '8050:80'
    # stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./src:/go/tmp/src

# docker-compose exec golang_first gofmt hello.go
# docker-compose exec golang_first go run hello.go
# docker-compose exec golang_first go run commands/runserver.go