version: '3.9'

services:

  golang_first:
    build: ./docker/go
    container_name: golang_first
    restart: always
    ports:
      - '8050:80'
    # stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./src:/go/tmp/src
    depends_on:
      - golang_postgres
    environment:
      - DB_PASSWORD=qwerty

  golang_postgres:
    restart: always
    image: postgres:latest
    volumes:
    - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432

# docker-compose exec golang_first gofmt hello.go
# docker-compose exec golang_first go run hello.go
# docker-compose exec golang_first go run commands/runserver.go postgres